### ISSUE TITLE
Can aptoide-uploader work as an offline App Store in rural Africa?

### ISSUE THREAD

**Issue by edresor** [Aptoide/aptoide-uploader#2]
I am not a programmer, so I may be totally confused by my hope to find an open source App Store that can run on an offline, Linux  server (preferably Ubuntu 14.04 64-bit server).

Can aptoide-uploader work as an offline App Store in rural Africa?

If this is possible with Aptoide-Uploader or another probgram, the server would be used for free educational apps in rural areas where connecting 20 tablets to the Google Play store is impossible or too expensive.

Thanks for your help. Ed

**Comment by edresor** [comment]
I see my mistake.  Aptoide-uploader is for uploading apps to an app store.
Sorry.

**Comment by TacoTheDank** [comment]
@edresor ill direct you to these if it isn't too late:
https://gitlab.com/AuroraOSS/AuroraStore
https://github.com/yeriomin/YalpStore
